### ISSUE TITLE
How did you visualzie the segemented images?

### ISSUE THREAD

**Issue by pw0300** [sacmehta/3D-ESPNet#3]
I have ran and altered the code to try another architecture, i wanted to see how the actual segmented images look like, and I couldn't find a code in your directory to do the same so I was wondering as to how you were able to do so.

**Comment by muween** [comment]
+1，how to make different label have different color? Or you just used a software ?

**Comment by sacmehta** [comment]
You can refer below file for visualizing results in color:

https://github.com/sacmehta/ESPNet/blob/master/test/VisualizeResults.py
